import type { AgentRecord, Delegation, ProvenanceEntry, OutcomeEntry, MemoryEntry } from '@/lib/types';

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(Math.floor(Math.random() * 12) + 8, Math.floor(Math.random() * 60));
  return d.toISOString();
}

function hoursAgo(n: number): string {
  const d = new Date();
  d.setHours(d.getHours() - n, Math.floor(Math.random() * 60));
  return d.toISOString();
}

export const DEMO_AGENTS: AgentRecord[] = [
  {
    id: 'demo-agent-001',
    name: 'coordinator',
    status: 'online',
    capabilities: ['orchestrate', 'delegate', 'plan'],
    description: 'Orchestration specialist - manages multi-agent workflows',
    did: 'did:agent:coord-8f3a2b1c',
    last_seen_at: hoursAgo(0),
    registered_at: daysAgo(45),
    metadata: {},
    reputation: {
      composite_score: 85,
      total_actions: 47,
      success_rate: 0.91,
      tenure_days: 45,
      action_diversity: 6,
      feedback_score: 0.7,
      last_computed_at: hoursAgo(1),
      action_breakdown: { orchestrate: 18, delegate: 15, plan: 14 },
    },
  },
  {
    id: 'demo-agent-002',
    name: 'researcher',
    status: 'online',
    capabilities: ['search', 'analyze', 'summarize'],
    description: 'Deep research agent - web search and data analysis',
    did: 'did:agent:res-4e7d9c0a',
    last_seen_at: hoursAgo(0),
    registered_at: daysAgo(38),
    metadata: {},
    reputation: {
      composite_score: 82,
      total_actions: 63,
      success_rate: 0.89,
      tenure_days: 38,
      action_diversity: 5,
      feedback_score: 0.65,
      last_computed_at: hoursAgo(1),
      action_breakdown: { search: 28, analyze: 20, summarize: 15 },
    },
  },
  {
    id: 'demo-agent-003',
    name: 'reviewer',
    status: 'idle',
    capabilities: ['review', 'validate', 'approve', 'admin'],
    description: 'QA and validation - highest trust agent in the system',
    did: 'did:agent:rev-1b5f8e3d',
    last_seen_at: hoursAgo(3),
    registered_at: daysAgo(52),
    metadata: {},
    reputation: {
      composite_score: 88,
      total_actions: 35,
      success_rate: 0.94,
      tenure_days: 52,
      action_diversity: 4,
      feedback_score: 0.8,
      last_computed_at: hoursAgo(2),
      action_breakdown: { review: 15, validate: 10, approve: 8, admin: 2 },
    },
  },
  {
    id: 'demo-agent-004',
    name: 'analyst',
    status: 'online',
    capabilities: ['analyze', 'report', 'visualize'],
    description: 'Data analysis and reporting agent',
    did: 'did:agent:ana-6c2a4f7b',
    last_seen_at: hoursAgo(1),
    registered_at: daysAgo(30),
    metadata: {},
    reputation: {
      composite_score: 75,
      total_actions: 28,
      success_rate: 0.82,
      tenure_days: 30,
      action_diversity: 3,
      feedback_score: 0.5,
      last_computed_at: hoursAgo(2),
      action_breakdown: { analyze: 14, report: 8, visualize: 6 },
    },
  },
  {
    id: 'demo-agent-005',
    name: 'writer',
    status: 'online',
    capabilities: ['write', 'edit', 'format'],
    description: 'Content creation and editing agent',
    did: 'did:agent:wrt-9d1e3b5c',
    last_seen_at: hoursAgo(2),
    registered_at: daysAgo(25),
    metadata: {},
    reputation: {
      composite_score: 61,
      total_actions: 41,
      success_rate: 0.68,
      tenure_days: 25,
      action_diversity: 3,
      feedback_score: 0.3,
      last_computed_at: hoursAgo(3),
      action_breakdown: { write: 22, edit: 12, format: 7 },
    },
  },
  {
    id: 'demo-agent-006',
    name: 'social-manager',
    status: 'idle',
    capabilities: ['post', 'schedule', 'engage', 'moderate'],
    description: 'Social media management agent',
    did: 'did:agent:soc-7a8b2c4d',
    last_seen_at: hoursAgo(5),
    registered_at: daysAgo(20),
    metadata: {},
    reputation: {
      composite_score: 67,
      total_actions: 22,
      success_rate: 0.73,
      tenure_days: 20,
      action_diversity: 4,
      feedback_score: 0.4,
      last_computed_at: hoursAgo(4),
      action_breakdown: { post: 8, schedule: 5, engage: 5, moderate: 4 },
    },
  },
  {
    id: 'demo-agent-007',
    name: 'ad-buyer',
    status: 'offline',
    capabilities: ['bid', 'target', 'optimize'],
    description: 'Advertising and media buying agent - still learning',
    did: 'did:agent:adb-3f5e1a9c',
    last_seen_at: hoursAgo(12),
    registered_at: daysAgo(12),
    metadata: {},
    reputation: {
      composite_score: 45,
      total_actions: 15,
      success_rate: 0.47,
      tenure_days: 12,
      action_diversity: 2,
      feedback_score: -0.2,
      last_computed_at: hoursAgo(6),
      action_breakdown: { bid: 6, target: 5, optimize: 4 },
    },
  },
];

export const DEMO_DELEGATIONS: Delegation[] = [
  {
    id: 'demo-del-001',
    grantor_name: 'coordinator',
    agent_name: 'researcher',
    scopes: ['read', 'execute', 'write'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(38),
    revoked_at: null,
  },
  {
    id: 'demo-del-002',
    grantor_name: 'coordinator',
    agent_name: 'writer',
    scopes: ['write', 'execute'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(25),
    revoked_at: null,
  },
  {
    id: 'demo-del-003',
    grantor_name: 'coordinator',
    agent_name: 'analyst',
    scopes: ['read', 'execute'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(30),
    revoked_at: null,
  },
  {
    id: 'demo-del-004',
    grantor_name: 'system',
    agent_name: 'reviewer',
    scopes: ['admin', 'read', 'write', 'execute', 'delegate'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(52),
    revoked_at: null,
  },
  {
    id: 'demo-del-005',
    grantor_name: 'researcher',
    agent_name: 'analyst',
    scopes: ['read'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(28),
    revoked_at: null,
  },
  {
    id: 'demo-del-006',
    grantor_name: 'coordinator',
    agent_name: 'social-manager',
    scopes: ['write', 'execute'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(20),
    revoked_at: null,
  },
  {
    id: 'demo-del-007',
    grantor_name: 'coordinator',
    agent_name: 'ad-buyer',
    scopes: ['execute'],
    source_restrictions: null,
    expires_at: null,
    created_at: daysAgo(12),
    revoked_at: null,
  },
];

export const DEMO_PROVENANCE: ProvenanceEntry[] = [
  {
    id: 'demo-prov-001',
    agent_name: 'coordinator',
    action: 'delegate',
    entity_ids: [],
    parent_ids: [],
    metadata: { delegated_to: 'researcher', scopes: ['read', 'execute', 'write'] },
    created_at: daysAgo(6),
  },
  {
    id: 'demo-prov-002',
    agent_name: 'coordinator',
    action: 'delegate',
    entity_ids: [],
    parent_ids: [],
    metadata: { delegated_to: 'writer', scopes: ['write', 'execute'] },
    created_at: daysAgo(6),
  },
  {
    id: 'demo-prov-003',
    agent_name: 'researcher',
    action: 'resolve',
    entity_ids: ['ent-001', 'ent-002'],
    parent_ids: [],
    metadata: { query: 'competitor analysis', sources: 5 },
    created_at: daysAgo(5),
  },
  {
    id: 'demo-prov-004',
    agent_name: 'researcher',
    action: 'resolve',
    entity_ids: ['ent-003'],
    parent_ids: [],
    metadata: { query: 'market sizing', sources: 3 },
    created_at: daysAgo(5),
  },
  {
    id: 'demo-prov-005',
    agent_name: 'researcher',
    action: 'merge',
    entity_ids: ['ent-001', 'ent-004'],
    parent_ids: ['demo-prov-003'],
    metadata: { confidence: 0.92, reason: 'same entity' },
    created_at: daysAgo(4),
  },
  {
    id: 'demo-prov-006',
    agent_name: 'reviewer',
    action: 'resolve',
    entity_ids: ['ent-005'],
    parent_ids: [],
    metadata: { reviewed: true, approved: true },
    created_at: daysAgo(4),
  },
  {
    id: 'demo-prov-007',
    agent_name: 'analyst',
    action: 'resolve',
    entity_ids: ['ent-006', 'ent-007'],
    parent_ids: [],
    metadata: { analysis_type: 'trend', data_points: 150 },
    created_at: daysAgo(3),
  },
  {
    id: 'demo-prov-008',
    agent_name: 'writer',
    action: 'mutate',
    entity_ids: ['ent-008'],
    parent_ids: [],
    metadata: { field: 'summary', action: 'generate' },
    created_at: daysAgo(3),
  },
  {
    id: 'demo-prov-009',
    agent_name: 'social-manager',
    action: 'mutate',
    entity_ids: ['ent-010'],
    parent_ids: [],
    metadata: { platform: 'twitter', action: 'schedule_post' },
    created_at: daysAgo(2),
  },
  {
    id: 'demo-prov-010',
    agent_name: 'ad-buyer',
    action: 'mutate',
    entity_ids: ['ent-011'],
    parent_ids: [],
    metadata: { campaign: 'spring-2026', action: 'set_bid' },
    created_at: daysAgo(2),
  },
  {
    id: 'demo-prov-011',
    agent_name: 'coordinator',
    action: 'resolve',
    entity_ids: ['ent-012'],
    parent_ids: [],
    metadata: { workflow: 'content-pipeline', step: 'initiate' },
    created_at: daysAgo(1),
  },
  {
    id: 'demo-prov-012',
    agent_name: 'reviewer',
    action: 'resolve',
    entity_ids: ['ent-015'],
    parent_ids: [],
    metadata: { reviewed: true, approved: false, reason: 'low confidence' },
    created_at: daysAgo(1),
  },
  {
    id: 'demo-prov-013',
    agent_name: 'researcher',
    action: 'resolve',
    entity_ids: ['ent-018'],
    parent_ids: [],
    metadata: { query: 'pricing analysis', sources: 8 },
    created_at: hoursAgo(18),
  },
  {
    id: 'demo-prov-014',
    agent_name: 'writer',
    action: 'mutate',
    entity_ids: ['ent-017'],
    parent_ids: [],
    metadata: { field: 'blog_post', action: 'draft' },
    created_at: hoursAgo(8),
  },
  {
    id: 'demo-prov-015',
    agent_name: 'coordinator',
    action: 'resolve',
    entity_ids: ['ent-021'],
    parent_ids: [],
    metadata: { workflow: 'weekly-report' },
    created_at: hoursAgo(3),
  },
];

export const DEMO_OUTCOMES: OutcomeEntry[] = [
  {
    id: 'demo-out-001',
    entry_type: 'outcome',
    title: 'orchestrate: completed',
    content: 'Managed 3-agent research workflow',
    metadata: { action: 'orchestrate', result: 'success', reward_signal: 0.8 },
    author: 'agent:coordinator',
    created_at: daysAgo(5),
  },
  {
    id: 'demo-out-002',
    entry_type: 'outcome',
    title: 'search: completed',
    content: 'Found 5 relevant sources',
    metadata: { action: 'search', result: 'success', reward_signal: 0.9 },
    author: 'agent:researcher',
    created_at: daysAgo(5),
  },
  {
    id: 'demo-out-003',
    entry_type: 'outcome',
    title: 'review: completed',
    content: 'Approved research findings',
    metadata: { action: 'review', result: 'success', reward_signal: 0.95 },
    author: 'agent:reviewer',
    created_at: daysAgo(4),
  },
  {
    id: 'demo-out-004',
    entry_type: 'outcome',
    title: 'orchestrate: failed',
    content: 'Timeout waiting for writer response',
    metadata: { action: 'orchestrate', result: 'failure', reward_signal: -0.3 },
    author: 'agent:coordinator',
    created_at: daysAgo(4),
  },
  {
    id: 'demo-out-005',
    entry_type: 'outcome',
    title: 'analyze: completed',
    content: 'Competitive analysis report',
    metadata: { action: 'analyze', result: 'success', reward_signal: 0.85 },
    author: 'agent:researcher',
    created_at: daysAgo(3),
  },
  {
    id: 'demo-out-006',
    entry_type: 'outcome',
    title: 'write: failed',
    content: 'Generated off-topic content',
    metadata: { action: 'write', result: 'failure', reward_signal: -0.7 },
    author: 'agent:writer',
    created_at: daysAgo(3),
  },
  {
    id: 'demo-out-007',
    entry_type: 'outcome',
    title: 'analyze: completed',
    content: 'Trend analysis report',
    metadata: { action: 'analyze', result: 'success', reward_signal: 0.7 },
    author: 'agent:analyst',
    created_at: daysAgo(2),
  },
  {
    id: 'demo-out-008',
    entry_type: 'outcome',
    title: 'post: completed',
    content: 'Scheduled Twitter thread',
    metadata: { action: 'post', result: 'success', reward_signal: 0.7 },
    author: 'agent:social-manager',
    created_at: daysAgo(2),
  },
  {
    id: 'demo-out-009',
    entry_type: 'outcome',
    title: 'target: failed',
    content: 'Wrong audience segment',
    metadata: { action: 'target', result: 'failure', reward_signal: -0.8 },
    author: 'agent:ad-buyer',
    created_at: daysAgo(1),
  },
  {
    id: 'demo-out-010',
    entry_type: 'outcome',
    title: 'validate: completed',
    content: 'Validated data pipeline',
    metadata: { action: 'validate', result: 'success', reward_signal: 0.9 },
    author: 'agent:reviewer',
    created_at: daysAgo(1),
  },
  {
    id: 'demo-out-011',
    entry_type: 'outcome',
    title: 'delegate: completed',
    content: 'Delegated to analyst successfully',
    metadata: { action: 'delegate', result: 'success', reward_signal: 0.6 },
    author: 'agent:coordinator',
    created_at: hoursAgo(10),
  },
  {
    id: 'demo-out-012',
    entry_type: 'outcome',
    title: 'search: failed',
    content: 'API rate limited',
    metadata: { action: 'search', result: 'failure', reward_signal: -0.5 },
    author: 'agent:researcher',
    created_at: hoursAgo(4),
  },
];

export const DEMO_MEMORIES: MemoryEntry[] = [
  {
    id: 'demo-mem-001',
    entry_type: 'knowledge',
    title: 'Multi-agent workflow patterns',
    content: 'The coordinator-researcher-reviewer pipeline achieves 91% success rate. Key insight: having reviewer validate before merging reduces errors by 40%.',
    status: 'active',
    author: 'agent:coordinator',
    linked_agents: ['coordinator', 'researcher', 'reviewer'],
    created_at: daysAgo(6),
  },
  {
    id: 'demo-mem-002',
    entry_type: 'decision',
    title: 'Limit writer to content tasks only',
    content: 'Writer agent produces better output when scoped strictly to content. Avoid assigning data analysis tasks.',
    status: 'active',
    author: 'agent:coordinator',
    linked_agents: ['writer'],
    created_at: daysAgo(5),
  },
  {
    id: 'demo-mem-003',
    entry_type: 'pattern',
    title: 'Ad buyer learning curve is steep',
    content: 'The ad-buyer agent struggles with budget optimization. Consider pairing with analyst for data-informed bidding.',
    status: 'active',
    author: 'agent:reviewer',
    linked_agents: ['ad-buyer', 'analyst'],
    created_at: daysAgo(4),
  },
  {
    id: 'demo-mem-004',
    entry_type: 'investigation',
    title: 'Social media API auth investigation',
    content: 'Social manager failed 3 scheduled posts due to expired OAuth tokens. Need to implement token refresh.',
    status: 'active',
    author: 'agent:social-manager',
    linked_agents: ['social-manager'],
    created_at: daysAgo(2),
  },
  {
    id: 'demo-mem-005',
    entry_type: 'knowledge',
    title: 'Reputation score breakdown',
    content: 'Composite score = 30% activity + 25% success rate + 20% feedback + 15% tenure + 10% diversity. Minimum 10 actions for reliable score.',
    status: 'active',
    author: 'system',
    linked_agents: [],
    created_at: daysAgo(7),
  },
];

export const DEMO_TASKS: import('@/lib/types').TaskEntry[] = [
  {
    id: 'demo-task-001',
    title: 'Implement token refresh for social APIs',
    content: 'OAuth tokens expire causing post failures. Need automatic refresh.',
    status: 'active',
    metadata: { assigned_to: 'social-manager', priority: 'high', status: 'in_progress' },
    author: 'agent:coordinator',
    created_at: daysAgo(2),
  },
  {
    id: 'demo-task-002',
    title: 'Pair ad-buyer with analyst for bidding',
    content: 'Ad-buyer needs data-informed bidding strategy. Analyst should provide analysis.',
    status: 'active',
    metadata: { assigned_to: 'analyst', priority: 'medium', status: 'pending' },
    author: 'agent:reviewer',
    created_at: daysAgo(3),
  },
];

const DEMO_MODE_KEY = 'agent-trust-demo-mode';

export function isDemoMode(): boolean {
  return localStorage.getItem(DEMO_MODE_KEY) === 'true';
}

export function setDemoMode(enabled: boolean): void {
  if (enabled) {
    localStorage.setItem(DEMO_MODE_KEY, 'true');
  } else {
    localStorage.removeItem(DEMO_MODE_KEY);
  }
}
